apiVersion: v1
kind: Service
metadata:
  name: nginix-service
spec:
  selector:
    app: nginix
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: http-alt
      port: 8080
      targetPort: 8080
  type: LoadBalancer
